config/routes.rb
Rails.application.routes.draw do
  root 'staticpag#index'
  
  get 'staticpag/index'

  get 'staticpag/database'

  get 'staticpag/history'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyect.rb
class Proyect < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/staticpag_controller.rb
class StaticpagController < ApplicationController
  def index
  end

  def database
  end

  def history
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpag_helper.rb
module StaticpagHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <nav class="navbar">
  <div class="container-fluid">
  <div class="navbar-header">
  	<%=link_to "INDEX", staticpag_index_url, {:class=>"navbar-brand" } %>
  </div>
    
    <ul class="nav navbar-nav">
      
      <li><%=link_to "DataBase", staticpag_database_url, {:class=>"colornav" }  %></li>
      <li><%=link_to "History", staticpag_history_url, {:class=>"colornav" }  %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
<footer>
  <%= image_tag (footer/in.jpg) do%>
</footer>
    <%= yield %>
  </body>
</html>

app/views/staticpag/database.html.erb
<h1>Staticpag#database</h1>
<p>Find me in app/views/staticpag/database.html.erb</p>

app/views/staticpag/history.html.erb
<h1>Staticpag#history</h1>
<p>Find me in app/views/staticpag/history.html.erb</p>

app/views/staticpag/index.html.erb
<div class="container">
 <div class=" col-md-5">
 	<h1>Lorem Ipsum</h1>
 	<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ornare fringilla suscipit. Etiam bibendum nulla odio, eget consectetur risus iaculis id. Curabitur dignissim sem ut dui ullamcorper finibus. Etiam auctor sit amet enim quis dapibus. Fusce dictum ut ex vitae fermentum. Aliquam sit amet dolor quis ipsum bibendum malesuada sit amet vel sapien. Ut eu erat tempus, viverra nisl sed, hendrerit sem. 
 	 </p>

<p>
Vestibulum ut dolor in diam dictum euismod a ut nunc. Mauris pretium est at risus convallis, eu iaculis est porta. Donec rutrum rutrum mi venenatis fringilla. Donec eu ornare risus. Ut non molestie eros. Morbi gravida ornare sem. Vivamus malesuada nibh eu lectus pulvinar suscipit. Nunc sodales dui volutpat tortor ornare rhoncus. Vivamus euismod pretium vehicula. Vestibulum iaculis egestas augue, at porta erat elementum ut. </p>
 </div>
</div>